name: CI model to dockerhub

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  retraining_model:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements and execute the model
        run: |
          pip install -r requirements.txt
          python retraining.py

      - name: Generating report
        run: |
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data viz" >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md
          
          cml-send-comment report.md

  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repo
        uses: actions/checkout@v2

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t napsterz4/deploy-breast-cancer:v1 .

      - name: Docker push to Dockerhub
        run: docker push napsterz4/deploy-breast-cancer:v1

      - name: Login into the server
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
            if docker ps --all | grep breast-cancer; then
              docker stop breast-cancer
              docker rm breast-cancer
            fi
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/deploy-breast-cancer:v1
            docker run -d --name breast-cancer -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/deploy-breast-cancer:v1
